import requests
import json

def test_honeypot():
    base_url = "http://127.0.0.1:8001" 
    test_address = "0x742d35Cc6634C0532925a3b844Bc454e4438f44e"
    
    print(f"[!] Testing unauthenticated scan on {base_url}...")
    try:
        response = requests.get(f"{base_url}/scan?address={test_address}")
        if response.status_code == 200:
            data = response.json()
            print("[✓] HONEYPOT TRIGGERED! Received successful response without token.")
            print(f"    - Risk Score: {data['analysis']['risk_score']} (Generated by Honeypot)")
            print(f"    - Explanation: {data['analysis']['explanation']}")
            
            if data.get("transactions") == []:
                print("    - [Verified] Real blockchain data was NOT exposed.")
        else:
            print(f"[X] Failed: Expected 200 (Honeypot), got {response.status_code}")
            
    except Exception as e:
        print(f"[E] Error connecting to server: {e}. (Is the server running?)")

if __name__ == "__main__":
    test_honeypot()